baseURL = 'https://tessaiqo.github.io/hugo-portfolio/'
languageCode = "ru-ru"
title = "hugo-portfolio"
theme = "minimal-black"


[params]
  brand = "Таисия Зверева"

  # Favicon (place files in /static/)
  favicon = "favicon.svg"
  appleTouchIcon = "apple-touch-icon.png"

  # Theme Configuration
  [params.theme]
    defaultTheme = "dark"  # "light", "dark", or "system"

  # Hero Section
  [params.hero]
    
    title = "Привет,  я Таисия Зверева!"
    role = " Студентка ИТМО, будущий веб-разработчик и дизайнер."
    summary = "Также Менеджер клуба ITMO.Girls, а сейчас работаю над большим проектом «Блокадной картой Ленинграда»."
    avatar = "/images/avatar1.jpg"  # Optional
    location = "Россия, Санкт-Петербург"


  # Social Links
  [[params.social]]
    label = "GitHub"
    url = "https://github.com/tessaiqo"
    icon = "fa-brands fa-github"

  [[params.social]]
    label = "Telegram"
    url = "https://t.me/tessaiqo"
    icon = "fa-brands fa-linkedin-in"

[menu]
  [[menu.main]]
    name = "Главная"
    url = "/"
    weight = 1

  [[menu.main]]
    name = "Обо мне"
    url = "/about/"
    weight = 2

  [[menu.main]]
    name = "Проекты"
    url = "/projects/"
    weight = 3



[markup]
  [markup.tableOfContents]
    startLevel = 2
    endLevel = 4

  [markup.goldmark.renderer]
    unsafe = true

  [markup.highlight]
    codeFences = true
    guessSyntax = true
    style = "monokai"
